<?php

$labels = array();
$labels['autoresponder'] = 'Abwesenheitsnachricht';
$labels['autorespondersubject'] = 'Betreff';
$labels['autorespondermessage'] = 'Nachricht';
$labels['autoresponderexpires'] = 'Expires';
$labels['autoresponderdatefrom'] = 'Datum Beginn';
$labels['autoresponderdate'] = 'Datum Ende';
$labels['autoresponderenabled'] = 'Aktiviert';
$labels['dateformat'] = 'dd.mm.yyyy';
$labels['and'] = 'und';

$labels['autoresponder'] = 'Abwesenheitsnachricht';

$messages = array();
$messages['dateformatinconsistency'] = 'Datumsformat nicht korrekt';
$messages['entervalidmonth'] = 'Bitte geben Sie einen gültigen Monat ein.';
$messages['entervalidday'] = 'Bitte geben Sie einen gültigen Tag ein.';
$messages['enterfordigityear'] = 'Bitte geben Sie ein gültiges vierstelliges Jahr ein zwischen';
$messages['entervaliddate'] = 'Bitte geben Sie ein gültiges Datum ein.';
$messages['dateinpast'] = 'Datum liegt nicht in nder Zukunft. Es wird kein Ablauf gesetzt!';
$messages['subjectempty'] = 'Bitte geben Sie einen Betreff ein';
$messages['demoaccount'] = 'Dies ist ein Demo-Zugang. Abwesenheitsnachrichten sind nicht erlaubt.';

?>
