<?php

$labels = array();
$labels['autoresponder'] = 'Away message';
$labels['autorespondersubject'] = 'Subject';
$labels['autorespondermessage'] = 'Message';
$labels['autoresponderexpires'] = 'Expires';
$labels['autoresponderdate'] = 'Date';
$labels['autoresponderdatefrom'] = 'Valid since';
$labels['autoresponderenabled'] = 'Enabled';
$labels['dateformat'] = 'yyyy/mm/dd';
$labels['and'] = 'and';

$labels['autoresponder'] = 'Vacation';

$messages = array();
$messages['dateformatinconsistency'] = 'Date format is inconsistent';
$messages['entervalidmonth'] = 'Enter a valid month.';
$messages['entervalidday'] = 'Enter a valid day.';
$messages['enterfordigityear'] = 'Enter four digit year between';
$messages['entervaliddate'] = 'Enter a valid date.';
$messages['dateinpast'] = 'Date not in future. Expiration will be disabled!';
$messages['subjectempty'] = 'Please enter a subject';
$messages['demoaccount'] = 'This is a Demo Account. Away message is disallowed.';

?>
