<?php

$labels = array();
$labels['autoresponder'] = 'message d\'absence';
$labels['autorespondersubject'] = 'Sujet';
$labels['autorespondermessage'] = 'Message';
$labels['autoresponderexpires'] = 'Date d\'expiration';
$labels['autoresponderdate'] = 'Date';
$labels['autoresponderdatefrom'] = 'valide depuis';
$labels['autoresponderenabled'] = 'activer';
$labels['dateformat'] = 'yyyy/mm/dd';
$labels['and'] = 'et';

$labels['autoresponder'] = 'Absences';

$messages = array();
$messages['dateformatinconsistency'] = 'Le format de la date est incompatible';
$messages['entervalidmonth'] = 'Entrez un mois valide.';
$messages['entervalidday'] = 'Entrez un jour valide.';
$messages['enterfordigityear'] = 'Entrez l\'annee sur quatre chiffres';
$messages['entervaliddate'] = 'Entrez un date valide.';
$messages['dateinpast'] = 'Ne mettez pas de date dans le futur. La date d\'echeance sera desactive!';
$messages['subjectempty'] = 'Mettez un sujet, s\'il vous plait';
$messages['demoaccount'] = 'Il s\'agit d\'un compte de demonstration. Le message d\'absence est deactive.';

?>
