<?php

$labels = array();
$labels['autoresponder'] = 'Autoodpowiedź';
$labels['autorespondersubject'] = 'Temat';
$labels['autorespondermessage'] = 'Wiadomość';
$labels['autoresponderdate'] = 'Ważne do';
$labels['autoresponderdatefrom'] = 'Ważne od';
$labels['autoresponderenabled'] = 'Włączone';
$labels['dateformat'] = 'rrrr/mm/dd';
$labels['and'] = 'i';
$labels['autoresponder'] = 'Wakacje';

$messages = array();
$messages['dateformatinconsistency'] = 'Date format is inconsistent';
$messages['entervalidmonth'] = 'Enter a valid month.';
$messages['entervalidday'] = 'Enter a valid day.';
$messages['enterfordigityear'] = 'Enter four digit year between';
$messages['entervaliddate'] = 'Enter a valid date.';
$messages['dateinpast'] = 'Date not in future. Expiration will be disabled!';
$messages['subjectempty'] = 'Please enter a subject';
$messages['demoaccount'] = 'This is a Demo Account. Away message is disallowed.';

?>
