<?php

$labels = array();
$labels['autoresponder'] = 'Mensagem de Ausência';
$labels['autorespondersubject'] = 'Assunto';
$labels['autorespondermessage'] = 'Mensagem';
$labels['autoresponderexpires'] = 'Expiração';
$labels['autoresponderdate'] = 'Data';
$labels['autoresponderdatefrom'] = 'Válido desde';
$labels['autoresponderenabled'] = 'Ativo';
$labels['dateformat'] = 'yyyy/mm/dd';
$labels['and'] = 'e';

$labels['autoresponder'] = 'Ausência';

$messages = array();
$messages['dateformatinconsistency'] = 'O formato da data não é válido';
$messages['entervalidmonth'] = 'Insira um mês válido.';
$messages['entervalidday'] = 'Insira um dia válido.';
$messages['enterfordigityear'] = 'Insira os quatro dígitos do ano';
$messages['entervaliddate'] = 'Insira uma data válida.';
$messages['dateinpast'] = 'A data não se passa no futuro. A expiração não ficará ativa!';
$messages['subjectempty'] = 'Por favor insira o assunto';
$messages['demoaccount'] = 'Esta conta é apenas de demonstração. A mensagem de ausência não é permitida.';

?>
